---
- name: configuring tomcat on all servers  playbook3.yml
  hosts: all
  tasks:
    - name: install tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: install tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
    - name: copy users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
    - name: change tomcat port from 9090 to 8080
      replace: 
        regexp: 9090
        replace: 8080
        path: /etc/tomcat9/server.xml
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted
    - name: wait for some time
      pause:
        seconds: 60
    - name: check tomcat on server1
      uri: 
        url: http://172.31.41.47
        status_code: 200
    - name: check tomcat on server2
      uri:
        url: http://172.31.39.29
        status_code: 200
...
